apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- .git/info/exclude
- ConfigMap/gitlab-config.yaml
- ConfigMap/gitlab-runner.yaml
- DeploymentConfig/gitlab-postgresql.yaml
- DeploymentConfig/gitlab-redis.yaml
- DeploymentConfig/gitlab-runner.yaml
- DeploymentConfig/gitlab.yaml
- ImageStream/gitlab-redis.yaml
- ImageStream/gitlab-runner.yaml
- ImageStream/gitlab.yaml
- PersistentVolumeClaim/gitlab-artifacts.yaml
- PersistentVolumeClaim/gitlab-data.yaml
- PersistentVolumeClaim/gitlab-etc.yaml
- PersistentVolumeClaim/gitlab-pages.yaml
- PersistentVolumeClaim/gitlab-postgresql.yaml
- PersistentVolumeClaim/gitlab-redis-data.yaml
- Route/gitlab.yaml
- Service/gitlab-postgresql.yaml
- Service/gitlab-redis.yaml
- Service/gitlab.yaml
- ServiceAccount/gitlab-runner-user.yaml
- ServiceAccount/gitlab-user.yaml
