apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
  namespace: issc-lab
spec:
  tags:
  - from:
      kind: DockerImage
      name: gitlab/gitlab-ce:14.9.3-ce.0
    name: gitlab-14.9.3
