apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: "2022-04-15T14:44:04Z"
  labels:
    app: gitlab-ce
    app.kubernetes.io/component: gitlab-ce
    app.kubernetes.io/instance: gitlab-ce
  name: gitlab-ce
  namespace: issc-lab
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: sameersbn/gitlab
    from:
      kind: DockerImage
      name: sameersbn/gitlab
    generation: 2
    name: latest
    referencePolicy:
      type: Source
