apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2022-04-15T19:49:46Z"
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-runner
  namespace: issc-lab
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gitlab/gitlab-runner:v14.9.1
    generation: 4
    name: gitlab-runner-v14.9.1
    referencePolicy:
      type: Source
