apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-runner
  namespace: issc-lab
spec:
  tags:
  - from:
      kind: DockerImage
      name: gitlab/gitlab-runner:v14.9.1
    name: gitlab-runner-v14.9.1
