apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
spec:
  tags:
  - from:
      kind: DockerImage
      name: gitlab/gitlab-ce:12.4.8-ce.0
    name: gitlab-12.4.8
