apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-redis
  namespace: issc-lab
spec:
  tags:
  - from:
      kind: DockerImage
      name: redis:alpine3.15
    name: alpine3.15
