apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2022-04-15T19:58:14Z"
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-redis
  namespace: issc-lab
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: redis:alpine3.15
    generation: 4
    name: alpine3.15
    referencePolicy:
      type: Source
