apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2022-04-15T19:46:20Z"
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
  namespace: issc-lab
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gitlab/gitlab-ce:14.9.3-ce.0
    generation: 6
    name: gitlab-14.9.3
    referencePolicy:
      type: Source
