apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
  namespace: issc-lab
spec:
  replicas: 1
  selector:
    app: gitlab
    deploymentconfig: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        deploymentconfig: gitlab
    spec:
      containers:
      - env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              key: gitlab.rb
              name: gitlab-config
        image: gitlab-ce
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/liveness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: gitlab-ce
        ports:
        - containerPort: 22
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-ce-volume-1
        - mountPath: /gitlab-data
          name: gitlab-ce-volume-2
        - mountPath: /var/opt/gitlab/gitlab-rails/shared/artifacts
          name: gitlab-ce-volume-3
        - mountPath: /var/opt/gitlab/gitlab-rails/shared/pages
          name: gitlab-ce-volume-4
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: gitlab-user
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-ce-volume-1
        persistentVolumeClaim:
          claimName: gitlab-etc
      - name: gitlab-ce-volume-2
        persistentVolumeClaim:
          claimName: gitlab-data
      - name: gitlab-ce-volume-3
        persistentVolumeClaim:
          claimName: gitlab-artifacts
      - name: gitlab-ce-volume-4
        persistentVolumeClaim:
          claimName: gitlab-pages
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ce
      from:
        kind: ImageStreamTag
        name: gitlab:gitlab-14.9.3
    type: ImageChange
