apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-runner
spec:
  replicas: "1"
  selector:
    app: gitlab
    deploymentconfig: gitlab-runner
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: gitlab
        deploymentconfig: gitlab-runner
    spec:
      containers:
      - command:
        - /bin/bash
        - /scripts/entrypoint
        env:
        - name: REGISTRATION_TOKEN
          value: Dk3yfKKINvTUiMfd
        - name: REGISTER_LOCKED
          value: "false"
        - name: KUBERNETES_PRIVILEGED
          value: "true"
        - name: KUBERNETES_IMAGE
          value: ubuntu:16.04
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gitlab-runner
        imagePullPolicy: IfNotPresent
        name: gitlab-runner
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/gitlab-runner
          name: gitlab-runner-1
        - mountPath: /home/gitlab-runner
          name: gitlab-runner-2
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gitlab-runner-user
      serviceAccountName: gitlab-runner-user
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: gitlab-runner-1
      - emptyDir: {}
        name: gitlab-runner-2
      - configMap:
          defaultMode: 420
          name: gitlab-runner
        name: scripts
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-runner
      from:
        kind: ImageStreamTag
        name: gitlab-runner:gitlab-runner-v12.7.0
    type: ImageChange
