apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: gitlab-ce
    createdBy: gitlab-ce-template
  name: gitlab-ce-postgresql
  namespace: issc-lab
spec:
  replicas: 1
  selector:
    app: gitlab-ce
    deploymentconfig: gitlab-ce-postgresql
  strategy:
    recreateParams:
      post:
        execNewPod:
          command:
          - /usr/bin/scl
          - enable
          - rh-postgresql96
          - export PGPASSWORD='7fL8sC30mr5V6g1h'; psql -h 'gitlab-ce-postgresql' -U
            postgres -d gitlabhq_production -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'
          containerName: gitlab-ce-postgresql
          env:
          - name: HOME
            value: /var/lib/pgsql
          - name: PGDATA
            value: /var/lib/pgsql/data/userdata
          - name: CONTAINER_SCRIPTS_PATH
            value: /usr/share/container-scripts/postgresql
        failurePolicy: Retry
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab-ce
        deploymentconfig: gitlab-ce-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: userYIN
        - name: POSTGRESQL_PASSWORD
          value: QUuNM3EHQqAmakBk
        - name: POSTGRESQL_DATABASE
          value: gitlabhq_production
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: 7fL8sC30mr5V6g1h
        image: gitlab-ce-postgresql
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: gitlab-ce-postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: gitlab-ce-volume-3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-ce-volume-3
        persistentVolumeClaim:
          claimName: gitlab-ce-postgresql
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ce-postgresql
      from:
        kind: ImageStreamTag
        name: postgresql:10
        namespace: openshift
    type: ImageChange
