apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-redis
  namespace: issc-lab
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: gitlab
    deploymentconfig: gitlab-redis
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitlab
        deploymentconfig: gitlab-redis
    spec:
      containers:
      - args:
        - exec redis-server
        command:
        - /bin/sh
        - -ec
        image: redis@sha256:6c42cce2871e8dc5fb3e843ed5c4e7939d312faf5e53ff0ff4ca955a7e0b2b39
        imagePullPolicy: IfNotPresent
        name: gitlab-ce-redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: gitlab-ce-volume-4
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-ce-volume-4
        persistentVolumeClaim:
          claimName: gitlab-redis-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ce-redis
      from:
        kind: ImageStreamTag
        name: gitlab-redis:alpine3.15
        namespace: issc-lab
      lastTriggeredImage: redis@sha256:6c42cce2871e8dc5fb3e843ed5c4e7939d312faf5e53ff0ff4ca955a7e0b2b39
    type: ImageChange
