apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-redis
spec:
  replicas: 1
  selector:
    app: gitlab
    deploymentconfig: gitlab-redis
  strategy:
    recreateParams: {}
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        deploymentconfig: gitlab-redis
    spec:
      containers:
      - args:
        - exec redis-server
        command:
        - /bin/sh
        - -ec
        image: gitlab-ce-redis
        imagePullPolicy: IfNotPresent
        name: gitlab-ce-redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data
          name: gitlab-ce-volume-4
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-ce-volume-4
        persistentVolumeClaim:
          claimName: gitlab-redis-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ce-redis
      from:
        kind: ImageStreamTag
        name: gitlab-redis:3.2.3
    type: ImageChange
