apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-postgresql
  namespace: issc-lab
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    app: gitlab
    deploymentconfig: gitlab-postgresql
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      post:
        execNewPod:
          command:
          - /usr/bin/scl
          - enable
          - rh-postgresql96
          - export PGPASSWORD='f250mVVJDlxJ51Xj'; psql -h 'gitlab-postgresql' -U postgres
            -d gitlabhq_production -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'
          containerName: gitlab-ce-postgresql
          env:
          - name: HOME
            value: /tmp
          - name: PGDATA
            value: /var/lib/pgsql/data/userdata
          - name: CONTAINER_SCRIPTS_PATH
            value: /usr/share/container-scripts/postgresql
        failurePolicy: Retry
      timeoutSeconds: 600
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitlab
        deploymentconfig: gitlab-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: userNYW
        - name: POSTGRESQL_PASSWORD
          value: KibfSxS4AlGmWktL
        - name: POSTGRESQL_DATABASE
          value: gitlabhq_production
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: f250mVVJDlxJ51Xj
        - name: HOME
          value: /tmp
        image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql@sha256:5c4f5f52a37718a9a1997ba212ef172694475558c35232b56dac638529c5b569
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: gitlab-ce-postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: gitlab-ce-volume-3
        - mountPath: /var/lib/pgsql/data/userdata
          name: gitlab-ce-volume-3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-ce-volume-3
        persistentVolumeClaim:
          claimName: gitlab-postgresql
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ce-postgresql
      from:
        kind: ImageStreamTag
        name: postgresql:10
        namespace: openshift
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/openshift/postgresql@sha256:5c4f5f52a37718a9a1997ba212ef172694475558c35232b56dac638529c5b569
    type: ImageChange
