apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    createdBy: gitlab-ce-template
  name: gitlab-pages
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
