apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
  labels:
    createdBy: gitlab-ce-template
  name: gitlab-postgresql
  namespace: issc-lab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: vsphere-standard-xfs
  volumeName: pvc-66b169c4-cef4-47f2-a213-ca5235957750
