apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-redis
  namespace: gitlab
spec:
  ports:
  - name: 6379-redis
    port: 6379
  selector:
    app: gitlab
    deploymentconfig: gitlab-redis
