apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
  namespace: gitlab
spec:
  ports:
  - name: 22-ssh
    port: 22
  - name: 80-http
    port: 80
  selector:
    app: gitlab
    deploymentconfig: gitlab
