apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-ce
    createdBy: gitlab-ce-template
  name: gitlab-ce-postgresql
  namespace: issc-lab
spec:
  ports:
  - name: 5432-postgresql
    port: 5432
  selector:
    app: gitlab-ce
    deploymentconfig: gitlab-ce-postgresql
