apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
  namespace: issc-lab
spec:
  clusterIP: 172.30.47.173
  clusterIPs:
  - 172.30.47.173
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 22-ssh
    port: 22
  - name: 80-http
    port: 80
  selector:
    app: gitlab
    deploymentconfig: gitlab
