apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-redis
    app.kubernetes.io/component: gitlab-redis
    app.kubernetes.io/instance: gitlab-redis
    app.kubernetes.io/name: gitlab-redis
  name: gitlab-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    deployment: gitlab-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
