apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
spec:
  ports:
  - name: 22-ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: 80-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitlab
    deploymentconfig: gitlab
  sessionAffinity: None
  type: ClusterIP
