apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-ce
    createdBy: gitlab-ce-template
  name: gitlab-ce-redis
  namespace: issc-lab
spec:
  ports:
  - name: 6379-redis
    port: 6379
  selector:
    app: gitlab-ce
    deploymentconfig: gitlab-ce-redis
