apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-postgresql
  namespace: gitlab
spec:
  ports:
  - name: 5432-postgresql
    port: 5432
  selector:
    app: gitlab
    deploymentconfig: gitlab-postgresql
