apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab-postgresql
  namespace: issc-lab
spec:
  clusterIP: 172.30.25.34
  clusterIPs:
  - 172.30.25.34
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5432-postgresql
    port: 5432
  selector:
    app: gitlab
    deploymentconfig: gitlab-postgresql
