apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gitlab
    createdBy: gitlab-ce-template
  name: gitlab
spec:
  host: gitlab
  port:
    targetPort: 80-http
  to:
    kind: Service
    name: gitlab
