apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gitlab-ce
    createdBy: gitlab-ce-template
  name: gitlab-ce
  namespace: issc-lab
spec:
  host: gitlab-ce.apps.caas-oat.gdc.geodis.org
  port:
    targetPort: 80-http
  to:
    kind: Service
    name: gitlab-ce
