apiVersion: v1
data:
  gitlab.rb: |
    external_url "http://gitlab/"
    postgresql['enable']=false
    gitlab_rails['db_host'] = 'gitlab-postgresql'
    gitlab_rails['db_password']='KibfSxS4AlGmWktL'
    gitlab_rails['db_username']='userNYW'
    gitlab_rails['db_database']='gitlabhq_production'
    redis['enable'] = false
    gitlab_rails['redis_host']='gitlab-redis'
    unicorn['worker_processes'] = 2
    manage_accounts['enable'] = true
    manage_storage_directories['manage_etc'] = false
    gitlab_shell['auth_file'] = '/gitlab-data/ssh/authorized_keys'
    git_data_dirs({ 'default' => { 'path' => '/gitlab-data/git-data' } })
    gitlab_rails['shared_path'] = '/gitlab-data/shared'
    gitlab_rails['uploads_directory'] = '/gitlab-data/uploads'
    gitlab_ci['builds_directory'] = '/gitlab-data/builds'
    prometheus_monitoring['enable'] = false
    gitlab_rails['usage_ping_enabled'] = false
    gitlab_rails['initial_shared_runners_registration_token'] = "Dk3yfKKINvTUiMfd"
    gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
kind: ConfigMap
metadata:
  labels:
    createdBy: gitlab-ce-template
  name: gitlab-config
