apiVersion: v1
data:
  config.toml: |
    concurrent = 10
    check_interval = 10
  entrypoint: |
    #!/bin/bash
    set -xe
    cp /scripts/config.toml /etc/gitlab-runner/
    # Register the runner
    /entrypoint register --non-interactive \
      --url http://gitlab \
      --executor kubernetes
    # Add docker.sock volumes
    cat /scripts/volumes.toml >> /etc/gitlab-runner/config.toml
    # Start the runner
    /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner
  volumes.toml: |2
        [[runners.kubernetes.volumes.host_path]]
          name = "docker-sock"
          mount_path = "/var/run/docker.sock"
          host_path = "/var/run/docker.sock"
kind: ConfigMap
metadata:
  labels:
    createdBy: gitlab-ce-template
  name: gitlab-runner
